CREATE TABLE IF NOT EXISTS categories
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255),
    parent_id   INT NULL,

    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id)
            REFERENCES categories (id)
            ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS products
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255),
    price       FLOAT,
    image_url   VARCHAR(255),
    category_id INT REFERENCES categories (id),
    available   BOOLEAN
)